#+title: Org knit
#+author: TEC

Let someone else take care of keeping up to date tangled/woven versions of your
Org files for public consumption.

#+begin_src yaml
- name: Export org files
  uses: tecosaur/org-knit-action
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
#+end_src

* Parameters
+ =parameter= (=default=) :: description
** Exporting
+ =config= (=false=) :: Path to either an =init.el= file, or a repository url for =~/.emacs.d=.
  This also recognises Doom configuration repositories (=~/.config/doom=).
+ =setup_file= (=false=) :: URL for a =#+setupfile= to use in all Org files.
+ =eval= (=false=) :: Whether to evaluate code in Org files. Also accepts a list of
  globs specifying which Org files should be evaluated.
+ =tangle= (=false=) :: Whether to run ~org-tangle~ for each Org file. Also accepts a list of
  globs specifying which Org files should be tangled.
+ =export= (=html=) :: Comma separated list of formats to export to.
+ =files= (=**/*.org=) :: List of org file globs to act on.
** Publishing
+ =github_token= :: The =GITHUB_TOKEN= secret. Required to push any result.
+ =branch= (default branch) :: The branch to push files to
+ =force_orphan= (=false=) :: Force-push the created commit as the only commit on
  the branch.
+ =keep_files= (=true=) :: Whether to include non-org-related files. Also accepts a
  list of globs.
+ =commit_message= (=Knit: !#!=) :: Commit message to use. =!#!= is replaced with the
  triggering commit hash.
+ =fragile= (=true=) :: Fail the action if any export/tangle steps fail.
